spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    # repoURL: https://github.com/argoproj/argocd-example-apps
    repoURL: https://github.com/adimicoli-verisk/argocd-example-apps.git
    targetRevision: HEAD